default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: event_management
  password: password

development:
  <<: *default
  database: web_scraper

heroku:
  <<: *default
  url: <%= ENV.fetch('JAWSDB_URL', '').sub('mysql://', 'mysql2://') %>