development:
  telegram:
    # Single bot can be specified like this
    bot: 1601727768:AAFt0vu1lyLanNRTFtilkEN-AGElpUaioMg
    # or
    bot:
      token: 1601727768:AAFt0vu1lyLanNRTFtilkEN-AGElpUaioMg
      username: ChatBot
      # server: http://local.bot.api.server

    # For multiple bots in single app use hash of `internal_bot_id => settings`
    # bots:
    #   # just set the bot token
    #   chat: TOKEN_1
    #   # or add username to support commands with mentions (/help@ChatBot)
    #   auction:
    #     token: TOKEN_2
    #     username: ChatBot
