---
:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
:timeout: 30
:queues:
  - default
:schedule:
  ping_check_scheduler:
    every: '5m'
    class: PingCheckScheduler
  ping_report_scheduler:
    every: '30m'
    class: PingReportScheduler
